"""Generate the embedded alpha atlas from the extracted SkyUI frame SVG.

Requires Pillow and Inkscape. Run from any directory:
python tools/generate-skyui-frame.py --inkscape "C:/Program Files/Inkscape/bin/inkscape.com"
"""

import argparse
import subprocess
from pathlib import Path

from PIL import Image


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inkscape", default="inkscape")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    temporary = root / "build-new" / "skyui-artwork"
    temporary.mkdir(parents=True, exist_ok=True)
    png = temporary / "frame.png"
    subprocess.run(
        [args.inkscape, str(root / "assets/SkyUI/messagebox-frame.svg"),
         "--export-type=png", f"--export-filename={png}", "--export-dpi=384"],
        check=True,
    )
    with Image.open(png) as image:
        alpha = image.convert("RGBA").getchannel("A")
    if alpha.size != (1729, 619):
        raise ValueError(f"Unexpected raster dimensions {alpha.size}; check SVG bounds and export DPI.")

    # Shape bounds: (-4324,-1550)..(4322,1546) twips.
    # Original scaling grid: (-3751,-924)..(3724,960) twips.
    # Convert twips to pixels, then to the 4x raster (rounding to pixel boundaries).
    left, top, right, bottom = 115, 125, 1610, 502
    width, height = alpha.size
    slices = [
        (0, 0, left, top), (right, 0, width, top),
        (0, bottom, left, height), (right, bottom, width, height),
        (width // 2, 0, width // 2 + 4, top),
        (width // 2, bottom, width // 2 + 4, height),
        (0, height // 2, left, height // 2 + 4),
        (right, height // 2, width, height // 2 + 4),
    ]
    atlas = Image.new("L", (256, 512))
    rectangles = []
    for index, box in enumerate(slices):
        tile = alpha.crop(box)
        # Transparent gutters prevent sampling an adjacent slice.
        x, y = (index % 2) * 128 + 2, (index // 2) * 128 + 2
        atlas.paste(tile, (x, y))
        rectangles.append((x, y, tile.width, tile.height))
    atlas.save(temporary / "atlas.png")

    runs = []
    for value in atlas.tobytes():
        if runs and runs[-1][1] == value and runs[-1][0] < 65535:
            runs[-1][0] += 1
        else:
            runs.append([1, value])
    lines = [
        "// Generated by tools/generate-skyui-frame.py; do not edit by hand.",
        "// SkyUI messagebox.swf shape 10; see assets/SkyUI/README.md for attribution.",
        "#pragma once", "#include <cstdint>", "", "namespace Easy2Read::SkyUIFrame::Data {",
        "inline constexpr int Width = 256;", "inline constexpr int Height = 512;",
        "struct Slice { int x, y, width, height; };",
        "inline constexpr Slice Slices[] = {",
        *["    {%d, %d, %d, %d}," % rect for rect in rectangles],
        "};", "struct AlphaRun { std::uint16_t length; std::uint8_t alpha; };",
        "inline constexpr AlphaRun Alpha[] = {",
    ]
    for index in range(0, len(runs), 8):
        lines.append("    " + " ".join("{%d, %d}," % tuple(run) for run in runs[index:index + 8]))
    lines += ["};", "} // namespace Easy2Read::SkyUIFrame::Data", ""]
    (root / "src/UI/SkyUIFrameData.h").write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated 8 SkyUI slices: {len(runs)} alpha runs, {atlas.width}x{atlas.height} atlas.")


if __name__ == "__main__":
    main()
